name: Android Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign Release APK
        if: ${{ secrets.KEYSTORE_FILE != '' }}
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APKs
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/TypeKannada-v${{ steps.get_version.outputs.VERSION }}-debug.apk
          if [ -f "app/build/outputs/apk/release/app-release-unsigned-signed.apk" ]; then
            mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/TypeKannada-v${{ steps.get_version.outputs.VERSION }}-release.apk
          elif [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
            mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/TypeKannada-v${{ steps.get_version.outputs.VERSION }}-release-unsigned.apk
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/debug/TypeKannada-v${{ steps.get_version.outputs.VERSION }}-debug.apk
            app/build/outputs/apk/release/TypeKannada-v${{ steps.get_version.outputs.VERSION }}-release*.apk
          body: |
            ## Type Kannada v${{ steps.get_version.outputs.VERSION }}

            ### Changes in this Release
            - Check commit history for changes

            ### Download
            - **Debug APK**: For testing and development
            - **Release APK**: For production use

            ### Installation
            1. Download the APK
            2. Enable "Install from Unknown Sources" in Android settings
            3. Install the APK
            4. Enable the keyboard in Settings > Language & Input

            ### Font Styles Feature
            This version includes customizable Kannada font styles!
            - Open the app
            - Tap "Font Style" button
            - Choose your preferred font

            ---
            🤖 Generated with GitHub Actions
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apks
          path: app/build/outputs/apk/**/*.apk
          retention-days: 90
