name: Nightly Build

on:
  schedule:
    # Run at 2:00 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly:
    name: Nightly Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/TypeKannada-nightly-${{ steps.date.outputs.DATE }}.apk

      - name: Upload Nightly Build
        uses: actions/upload-artifact@v4
        with:
          name: nightly-build-${{ steps.date.outputs.DATE }}
          path: app/build/outputs/apk/debug/TypeKannada-nightly-${{ steps.date.outputs.DATE }}.apk
          retention-days: 7

      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '7 days'
          skip-recent: 3
